name: Bug report form
description: Document a bug or unexpected behavior
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Providing detailed information helps your fellow developers create the best possible solution! 🙌📈
  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What's the issue and how can we reproduce it? 🤔
      placeholder: |
        1. Login as ...
        2. Click on ...
        3. Observe that ...
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected behaviour
      description: What was supposed to happen?
      placeholder: Details and screenshots are very helpful!
    validations:
      required: true
  - type: dropdown
    id: device
    attributes:
      label: Device
      description: Does the issue occur on one or more types of devices/browsers/platforms?
      multiple: true
      options:
        - IDE/terminal
        - Desktop (Chrome/Edge/Opera)
        - Mac (Safari)
        - Android (Chrome/Edge/Opera)
        - iOS (Chrome/Safari)
        - Other, please specify somewhere
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion
      description: If you have any idea on how to fix the problem, share it! You can even use [spoiler tags](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) to hide your proposed solution ✨
      placeholder: |
        I think this could be fixed in App.vue by adding a new prop to ...
        ```vue
        // code ...
        ```
        Relevant documentation can be found at ...
  - type: markdown
    id: setlabel
    attributes:
      value: Finally, before submitting, remember to add relevant labels, e.g. `priority`, `backend` and/or `frontend`! 🚀