name: Bug report
description: Document a bug or unexpected behavior
title: "[BUG]"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Providing detailed information helps your fellow developers create the best possible solution! 🙌📈
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: ... and how can we reproduce the problem?
      placeholder: Specific details, filenames, and screenshots are all very helpful!
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: What did you expect to happen?
      description: ... or how is it supposed to work?
      placeholder: Short description of what you expected to happen
    validations:
      required: true
  - type: dropdown
    id: system
    attributes:
      label: Where are you seeing the problem?
      description: Can you find the same problem on other systems?
      multiple: true
      options:
        - IDE/terminal
        - Desktop (Chrome/Edge/Opera)
        - Mac (Safari)
        - Android (Chrome/Edge/Opera)
        - iOS (Chrome/Safari)
        - Other, please specify somewhere
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: suggestion
    attributes:
      label: Do you have a suggestion on how to fix it?
      description: If you have an idea on how to fix the problem, please share it! You can even use [spoiler tags](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) to hide your proposal ✨
      placeholder: |
        I think this could be fixed by...
        ```js
        // code goes here
        ```