name: Feature/enhancement suggestion form
description: A new feature or enhancement
body:
  - type: markdown
    attributes:
      value: |
        Providing detailed information helps your fellow developers create the best possible solution! 🙌📈
  - type: textarea
    id: background
    attributes:
      label: Background
      description: How would you describe the issue on a non-technical level? What do we gain by solving the issue? 💰
      placeholder: To give NTNUI more time to create the best moments as a student, we could ...
    validations:
      required: true
  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion
      description: If you have any idea on how to implement it, share it! You can even use [spoiler tags](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) to hide your proposed solution ✨
      placeholder: |
        I think that we could do something like, ...
        ```python
        def foo():
          # code
        ```
  - type: textarea
    id: documentation
    attributes:
      label: Documentation
      description: Relevant how-to's, former pull requests, articles or wikis that might help solve the problem ⚡
      placeholder: https://stackoverflow.com/questions/69...
  - type: markdown
    id: setlabel
    attributes:
      value: Finally, before submitting, remember to add relevant labels, e.g. `feature`, `enhancement`, `backend` and/or `frontend`! 🚀